name: run-tests
 on: [push]
 on:
 pull_request:
 env:
   GO_VERSION: 1.12.15
 jobs:
   test:
     name: Run Tests
     runs-on: ubuntu-latest
     steps:
     - name: set up go ${{env.GO_VERSION}}
       uses: actions/setup-go@v1
       with:
         go-version: ${{env.GO_VERSION}}
       id: go
     - name: Check out code into the Go module directory
       uses: actions/checkout@v1
       with:
         fetch-depth: 1
     - name: Build
       run: ./build.sh
     - name: Test
       run: go test -count=1 -v ./…
